spring:
  application:
    name: gateway-zuul
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 114.55.34.44:8848

eureka:
  client:
    fetchRegistry: true #\u6CE8\u518C\u5230\u522B\u7684\u670D\u52A1\uFF0C\u6240\u6709\u8BBE\u7F6E\u4E3Atrue
    registerWithEureka: true #\u9700\u8981\u53BB\u68C0\u7D22\u670D\u52A1\uFF0C\u6240\u6709\u8BBE\u7F6E\u4E3Atrue
    service-url:
      defaultZone: http://localhost:9000/eureka #\u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3\u7684\u914D\u7F6E\u5185\u5BB9\uFF0C\u6307\u5B9A\u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3\u7684\u4F4D\u7F6E
  #  instance:
  #    hostname: eureka-provider
  #    prefer-ip-address: true #\u4EE5ip\u5730\u5740\u6CE8\u518C\u5230\u670D\u52A1\u4E2D\u5FC3\uFF08\u5355\u8282\u70B9\u90E8\u7F72\u4E3A\u5206\u5E03\u5F0FEureka\u96C6\u7FA4\uFF0C\u7981\u6B62\u8BBE\u7F6E\u4E3Atrue\uFF09
  server:
    enable-self-preservation: false #\u662F\u5426\u5F00\u542F\u81EA\u6211\u4FDD\u62A4\u6A21\u5F0F
    eviction-interval-timer-in-ms: 60000 #\u670D\u52A1\u6CE8\u518C\u8868\u6E05\u7406\u95F4\u9694\uFF08\u5355\u4F4D\uFF1A\u6BEB\u79D2\uFF0C\u9ED8\u8BA460*1000\uFF09

server:
  port: 8080

zuul:
  # 前缀，可以用来做版本控制
  prefix: /v1
  # 禁用默认路由，执行配置的路由
  ignored-services: "*"
  routes:
    # 指定路由名称
    order:
      # 指定路由访问路径
      path: /order/**
      # 指定向下游服务转发请求头中携带的信息，例如head:tx-token
      sensitiveHeaders:
      # 自定义路由指向服务id
      serviceId: order-service
    # 路由排除访问路径
    ignored-patterns:
      - /order/getFilter/*
  # 添加代理头
  add-proxy-headers: true

